# Site Settings
title: "random thoughts"
description: "Dad of two, juggling love for cycling and technology. Spinning my wheels to catch up my kids."
url: "https://flavio.aiello.ch"
baseurl: ""
lang: "en"

# Social / SEO
social:
  name: Flavio Aiello
  links:
    - https://github.com/flavioaiello
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/me.jpg

# Author
author:
  name: "Flavio Aiello"
  bio: "Dad of two, juggling love for cycling and technology. Spinning my wheels to catch up my kids."
  avatar: "assets/images/me.jpg"
  location: "Switzerland"
  github: "flavioaiello"
  stackoverflow: "2474922/flavio"

# Comments
disqus: "flavioaiello"

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: rouge

# Permalink
permalink: /:title/

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - Rakefile
  - README.md
  - LICENSE.txt
  - magik-research.txt

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
